In [1]:
import numpy as np
from numpy.linalg import inv 

def estimate_beta(x, y):    
    beta_hat = (inv((x.T).dot(x))).dot(x.T).dot(y)
    
    return beta_hat

In [2]:
#x행렬에 intercept를 추가해야함
x = np.array([ [1, 0, 1],
               [1, 2, 3],
               [1, 3, 8]]) #3x3
y = np.transpose(np.array([1, 3, 7])) #3x1

In [3]:
x

array([[1, 0, 1],
       [1, 2, 3],
       [1, 3, 8]])

In [4]:
y

array([1, 3, 7])

In [5]:
estimate_beta(x,y)

array([0.25, 0.25, 0.75])

In [6]:
#sklearn은 디폴트로 intercept가 fit되므로, 데이터에 intercept가 포함된 경우는 fit_intercept=False로 해야함

In [7]:
from sklearn.linear_model import LinearRegression

In [8]:
reg = LinearRegression(fit_intercept=False).fit(x, y)

In [9]:
reg.coef_

array([0.25, 0.25, 0.75])