#### TOBIG'S 14기 정규세션 4주차 SVM 
### ASSIGNMENT1. Multiclass SVM 구현

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

# IRIS 데이터 로드
iris =  sns.load_dataset('iris') 
X= iris.iloc[:,:4] # 학습할 데이터
y = iris.iloc[:,-1] # 타겟
print(y)

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object


In [2]:
from sklearn.model_selection import train_test_split # train/test 데이터 분리
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=48)

In [3]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((120, 4), (30, 4), (120,), (30,))

In [4]:
scal = StandardScaler() # scaling
X_train = scal.fit_transform(X_train)
X_test = scal.transform(X_test)

In [5]:
y_train2 = y_train.copy()

In [6]:
y_train = pd.get_dummies(y_train) # one hot encoding

In [7]:
y_train

setosa  versicolor  virginica
110       0           0          1
69        0           1          0
148       0           0          1
39        1           0          0
53        0           1          0
..      ...         ...        ...
64        0           1          0
91        0           1          0
81        0           1          0
51        0           1          0
0         1           0          0

[120 rows x 3 columns]

In [8]:
# One VS Rest 구현을 위해 1) class가 0 or not 2) class가 1 or not을 구분하기 위한 머신 등을 미리 만들어주자
svm_1 = SVC(kernel ='rbf', C = 5, gamma = 5)
svm_2 = SVC(kernel ='rbf', C = 5, gamma = 5)
svm_3 = SVC(kernel ='rbf', C = 5, gamma = 5)

In [9]:
svm_1.fit(X_train,y_train.iloc[:,0]) # 데이터 클래스가 0 or not 구분해주는 머신
svm_2.fit(X_train,y_train.iloc[:,1]) # 데이터 클래스가 1 or not 구분해주는 머신
svm_3.fit(X_train,y_train.iloc[:,2]) # 데이터 클래스가 2 or not 구분해주는 머신

print(svm_1.predict(X_test)) # 데이터 클래스가 0 or not을 구분해주는 머신을 통해서 테스트 데이터의 클래스가 0인지, 0이 아닌인지 예측해보자
print(svm_1.decision_function(X_test)) # decision_function hyperplane과의 거리를 구하는 방법 (필요하다면 활용해주세요!)

[0 0 0 0 0 0 1 0 1 0 0 1 1 0 0 0 1 0 0 0 1 0 0 0 0 1 1 0 0 0]
[-1.12359969 -0.86782512 -0.65599247 -0.50194294 -0.76541147 -0.8819188
  1.07735938 -0.99156769  0.50201986 -0.9984315  -0.84532712  0.17062549
  0.34917127 -0.9813287  -0.72783399 -0.93313988  1.28153212 -0.56827872
 -0.73092732 -0.99670034  0.43553308 -0.96967771 -0.83939495 -1.03305682
 -0.75566609  1.13888006  0.42965012 -1.04268452 -0.93608147 -1.06090982]


In [10]:
print(svm_2.predict(X_test)) 
print(svm_2.decision_function(X_test)) # 1 or not : versicolor

[1 1 1 0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 1 1 0 0 0 0 0 1]
[ 1.37946585  0.64158717  0.08334644 -0.37103802 -0.2487255  -0.81469931
 -1.03237441 -0.865664   -0.79146099  0.98627485 -0.74374355 -0.65274563
 -0.72754177 -0.82140043  0.49349433  0.71459247 -1.11781529 -0.16565136
 -0.22738953 -0.99528903 -0.76367034 -0.98134121  0.10485724  1.07435138
 -0.5638643  -1.05835082 -0.76129344 -1.05493883 -0.89285055  1.17216254]


In [11]:
print(svm_3.predict(X_test)) 
print(svm_3.decision_function(X_test)) # 2 or not : virginica

[0 0 0 0 1 1 0 1 0 0 1 0 0 1 0 0 0 0 0 1 0 1 0 0 1 0 0 1 1 0]
[-1.27457139 -0.78526984 -0.4283019  -0.13015479  0.02100991  0.60666785
 -1.04453951  0.87392972 -0.71179178 -0.98399934  0.54318106 -0.51951719
 -0.623009    0.79694612 -0.76730253 -0.77830886 -1.16309745 -0.26885348
 -0.0392679   0.9921313  -0.67308697  0.91631483 -0.28552792 -1.03901081
  0.31617703 -1.08026876 -0.66965692  1.09785306  0.85212125 -1.10854399]


In [12]:
df = pd.DataFrame({
    '0_setosa' : svm_1.predict(X_test),
    '1_versicolor' : svm_2.predict(X_test),
    '2_virginica' : svm_3.predict(X_test)
})

df

0_setosa  1_versicolor  2_virginica
0          0             1            0
1          0             1            0
2          0             1            0
3          0             0            0
4          0             0            1
5          0             0            1
6          1             0            0
7          0             0            1
8          1             0            0
9          0             1            0
10         0             0            1
11         1             0            0
12         1             0            0
13         0             0            1
14         0             1            0
15         0             1            0
16         1             0            0
17         0             0            0
18         0             0            0
19         0             0            1
20         1             0            0
21         0             0            1
22         0             1            0
23         0             1            0
24         0             0            1
25         1             0            0
26         1             0            0
27         0             0            1
28         0             0            1
29         0             1            0

In [13]:
# 부호가 모든 같은 경우가 있는가? > 모두 동점인 경우가 생길 것
for i in range(len(X_test)):
    # ~. decision_function을 이용하면 해당 데이터가 하이퍼플레인으로부터 얼마나 떨어져있는지 '거리'가 나온다!
    # 다음은 그 값의 부호를 이용해 모두가 동점인 경우가 있는지 출력하는 함수 
    if np.sign(svm_1.decision_function(X_test)[i]) == np.sign(svm_2.decision_function(X_test)[i]) == np.sign(svm_3.decision_function(X_test)[i]) :
        print("index : ", i, ", [" , svm_1.decision_function(X_test)[i], svm_2.decision_function(X_test)[i], svm_3.decision_function(X_test)[i], "]")

index :  3 , [ -0.501942941666542 -0.37103802454813056 -0.13015479353708545 ]
index :  17 , [ -0.5682787223502039 -0.16565135660642064 -0.2688534783556169 ]
index :  18 , [ -0.7309273218870285 -0.22738953007706803 -0.03926789904316806 ]


### 1. One vs Rest 

In [14]:
svm = []

for i in range(len(X_test)):
    if ((np.sign(svm_1.decision_function(X_test)[i]) > 0) and (np.sign(svm_2.decision_function(X_test)[i]) < 0) and (np.sign(svm_3.decision_function(X_test)[i]) < 0)): 
        svm.append(0)
    elif ((np.sign(svm_2.decision_function(X_test)[i]) > 0) and (np.sign(svm_1.decision_function(X_test)[i]) < 0) and (np.sign(svm_3.decision_function(X_test)[i]) < 0)): 
        svm.append(1) 
    elif ((np.sign(svm_3.decision_function(X_test)[i]) > 0) and (np.sign(svm_1.decision_function(X_test)[i]) < 0) and (np.sign(svm_2.decision_function(X_test)[i]) < 0)): 
        svm.append(2) 
    else:
        lst = [svm_1.decision_function(X_test)[i], svm_2.decision_function(X_test)[i], svm_3.decision_function(X_test)[i]]
        svm.append(list(map(abs, lst)).index(min(map(abs, lst))))

In [15]:
result = ["setosa" if s == 0 else "versicolor" if s == 1 else "virginica" for s in svm]
result 

['versicolor',
 'versicolor',
 'versicolor',
 'virginica',
 'virginica',
 'virginica',
 'setosa',
 'virginica',
 'setosa',
 'versicolor',
 'virginica',
 'setosa',
 'setosa',
 'virginica',
 'versicolor',
 'versicolor',
 'setosa',
 'versicolor',
 'virginica',
 'virginica',
 'setosa',
 'virginica',
 'versicolor',
 'versicolor',
 'virginica',
 'setosa',
 'setosa',
 'virginica',
 'virginica',
 'versicolor']

In [16]:
import sklearn.metrics as metrics
metrics.accuracy_score(y_test, result)

0.8666666666666667

### 2. One vs One 

In [17]:
# One VS One 구현 : 0_setosa, 1_versicolor, 2_virginica
svm_4 = SVC(kernel ='rbf', C = 5, gamma = 5, decision_function_shape = 'ovo') # 0 vs 1 
svm_5 = SVC(kernel ='rbf', C = 5, gamma = 5, decision_function_shape = 'ovo') # 1 vs 2 
svm_6 = SVC(kernel ='rbf', C = 5, gamma = 5, decision_function_shape = 'ovo') # 2 vs 0 

In [18]:
svm_4.fit(X_train,y_train.iloc[:,0]) # 데이터 클래스가 0 or 1
svm_5.fit(X_train,y_train.iloc[:,1]) # 데이터 클래스가 1 or 2
svm_6.fit(X_train,y_train.iloc[:,2]) # 데이터 클래스가 2 or 0

print(svm_4.predict(X_test)) # 데이터 클래스가 0 or not을 구분해주는 머신을 통해서 테스트 데이터의 클래스가 0인지, 0이 아닌인지 예측해보자
print(svm_4.decision_function(X_test)) # decision_function hyperplane과의 거리를 구하는 방법 (필요하다면 활용해주세요!)

[0 0 0 0 0 0 1 0 1 0 0 1 1 0 0 0 1 0 0 0 1 0 0 0 0 1 1 0 0 0]
[-1.12359969 -0.86782512 -0.65599247 -0.50194294 -0.76541147 -0.8819188
  1.07735938 -0.99156769  0.50201986 -0.9984315  -0.84532712  0.17062549
  0.34917127 -0.9813287  -0.72783399 -0.93313988  1.28153212 -0.56827872
 -0.73092732 -0.99670034  0.43553308 -0.96967771 -0.83939495 -1.03305682
 -0.75566609  1.13888006  0.42965012 -1.04268452 -0.93608147 -1.06090982]


In [19]:
print(svm_5.predict(X_test)) 
print(svm_5.decision_function(X_test)) # 1 or not : versicolor

[1 1 1 0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 1 1 0 0 0 0 0 1]
[ 1.37946585  0.64158717  0.08334644 -0.37103802 -0.2487255  -0.81469931
 -1.03237441 -0.865664   -0.79146099  0.98627485 -0.74374355 -0.65274563
 -0.72754177 -0.82140043  0.49349433  0.71459247 -1.11781529 -0.16565136
 -0.22738953 -0.99528903 -0.76367034 -0.98134121  0.10485724  1.07435138
 -0.5638643  -1.05835082 -0.76129344 -1.05493883 -0.89285055  1.17216254]


In [20]:
print(svm_6.predict(X_test)) 
print(svm_6.decision_function(X_test)) # 2 or not : virginica

[0 0 0 0 1 1 0 1 0 0 1 0 0 1 0 0 0 0 0 1 0 1 0 0 1 0 0 1 1 0]
[-1.27457139 -0.78526984 -0.4283019  -0.13015479  0.02100991  0.60666785
 -1.04453951  0.87392972 -0.71179178 -0.98399934  0.54318106 -0.51951719
 -0.623009    0.79694612 -0.76730253 -0.77830886 -1.16309745 -0.26885348
 -0.0392679   0.9921313  -0.67308697  0.91631483 -0.28552792 -1.03901081
  0.31617703 -1.08026876 -0.66965692  1.09785306  0.85212125 -1.10854399]


In [21]:
df = pd.DataFrame({
    '0_setosa' : svm_4.predict(X_test),
    '1_versicolor' : svm_5.predict(X_test),
    '2_virginica' : svm_6.predict(X_test)
})

df

0_setosa  1_versicolor  2_virginica
0          0             1            0
1          0             1            0
2          0             1            0
3          0             0            0
4          0             0            1
5          0             0            1
6          1             0            0
7          0             0            1
8          1             0            0
9          0             1            0
10         0             0            1
11         1             0            0
12         1             0            0
13         0             0            1
14         0             1            0
15         0             1            0
16         1             0            0
17         0             0            0
18         0             0            0
19         0             0            1
20         1             0            0
21         0             0            1
22         0             1            0
23         0             1            0
24         0             0            1
25         1             0            0
26         1             0            0
27         0             0            1
28         0             0            1
29         0             1            0

In [22]:
# 부호가 모든 같은 경우가 있는가? > 모두 동점인 경우가 생길 것
for i in range(len(X_test)):
    # ~. decision_function을 이용하면 해당 데이터가 하이퍼플레인으로부터 얼마나 떨어져있는지 '거리'가 나온다!
    # 다음은 그 값의 부호를 이용해 모두가 동점인 경우가 있는지 출력하는 함수 
    if np.sign(svm_4.decision_function(X_test)[i]) == np.sign(svm_5.decision_function(X_test)[i]) == np.sign(svm_6.decision_function(X_test)[i]) :
        print("index : ", i, ", [" , svm_4.decision_function(X_test)[i], svm_5.decision_function(X_test)[i], svm_6.decision_function(X_test)[i], "]")

index :  3 , [ -0.501942941666542 -0.37103802454813056 -0.13015479353708545 ]
index :  17 , [ -0.5682787223502039 -0.16565135660642064 -0.2688534783556169 ]
index :  18 , [ -0.7309273218870285 -0.22738953007706803 -0.03926789904316806 ]


In [23]:
svm2 = []

for i in range(len(X_test)):
    if ((np.sign(svm_4.decision_function(X_test)[i]) > 0) and (np.sign(svm_5.decision_function(X_test)[i]) < 0) and (np.sign(svm_6.decision_function(X_test)[i]) < 0)): 
        svm2.append(0)
    elif ((np.sign(svm_5.decision_function(X_test)[i]) > 0) and (np.sign(svm_4.decision_function(X_test)[i]) < 0) and (np.sign(svm_6.decision_function(X_test)[i]) < 0)): 
        svm2.append(1) 
    elif ((np.sign(svm_6.decision_function(X_test)[i]) > 0) and (np.sign(svm_4.decision_function(X_test)[i]) < 0) and (np.sign(svm_5.decision_function(X_test)[i]) < 0)): 
        svm2.append(2) 
    else:
        lst = [svm_4.decision_function(X_test)[i], svm_5.decision_function(X_test)[i], svm_6.decision_function(X_test)[i]]
        svm2.append(list(map(abs, lst)).index(min(map(abs, lst))))

In [24]:
result2 = ["setosa" if s == 0 else "versicolor" if s == 1 else "virginica" for s in svm2]
result2 

['versicolor',
 'versicolor',
 'versicolor',
 'virginica',
 'virginica',
 'virginica',
 'setosa',
 'virginica',
 'setosa',
 'versicolor',
 'virginica',
 'setosa',
 'setosa',
 'virginica',
 'versicolor',
 'versicolor',
 'setosa',
 'versicolor',
 'virginica',
 'virginica',
 'setosa',
 'virginica',
 'versicolor',
 'versicolor',
 'virginica',
 'setosa',
 'setosa',
 'virginica',
 'virginica',
 'versicolor']

In [25]:
metrics.accuracy_score(y_test, result2)

0.8666666666666667

## 3. sklearn 라이브러리와 비교 

In [26]:
# 기존 라이브러리가 제공하는 multi class SVM과 여러분이 구현한 multiclass SVM 결과를 비교해주세요
svm_7 = SVC(kernel ='rbf', C = 5, gamma = 5)
svm_7.fit(X_train, y_train2)
y_pred = svm_7.predict(X_test)

metrics.accuracy_score(y_test, y_pred)

0.8666666666666667